// One layout for all PnL cards; only theme tokens change. All positions are px on a 1080x1350
// canvas. Scale by (renderWidth / 1080).
// Themes without a background image yet fall back to the `fallback` gradient.

export const CARD_LAYOUT = {
  canvas: { width: 1080, height: 1350 },
  padding: 80,
  logo: { x: 80, y: 80, size: 80 },
  brand: { x: 180, y: 100, fontSize: 40, weight: "700", text: "CoinRadar" },
  statusPill: { right: 80, y: 88, height: 64, fontSize: 28, radius: 32 },
  symbol: { x: 80, y: 330, fontSize: 56, weight: "700" },
  sidePill: { gap: 20, height: 64, fontSize: 34, radius: 14 },
  pnlPercent: { x: 72, y: 410, fontSize: 200, weight: "800" },
  pnlUsd: { x: 80, y: 650, fontSize: 64, weight: "600" },
  divider: { x: 80, y: 975, thickness: 2 },
  stats: { y: 1005, labelSize: 26, valueGap: 44, valueSize: 50, columns: [80, 420, 760] },
  footer: { y: 1222, fontSize: 28 },
} as const;

export const CARD_THEMES = {
  minimal: {
    label: "Minimal",
    text: "#111118",
    sub: "#6B7082",
    profit: "#16A34A",
    loss: "#DC2626",
    pillBg: "#FFFFFF",
    pillText: "#111118",
    pillBorder: "#D3D5DF",
    divider: "#D3D5DF",
    shadow: false,
    fallback: ["#FFFFFF", "#F4F4F6"],
    background: undefined,
  },
  bold: {
    label: "Bold",
    text: "#FFFFFF",
    sub: "#A3A3A3",
    profit: "#C6F432",
    loss: "#FF4D4D",
    pillBg: "#C6F432",
    pillText: "#050505",
    pillBorder: "#C6F432",
    divider: "#2A2A2A",
    shadow: false,
    fallback: ["#0A0A0A", "#0A0A0A"],
    background: undefined,
  },
  neon: {
    label: "Neon",
    text: "#FFFFFF",
    sub: "#A5A3C9",
    profit: "#22D3EE",
    loss: "#FB7185",
    pillBg: "#1E1650",
    pillText: "#E0F7FF",
    pillBorder: "#22D3EE",
    divider: "#3A2F7A",
    shadow: true,
    fallback: ["#06060F", "#0E0A22"],
    background: undefined,
  },
  gradient: {
    label: "Gradient",
    text: "#FFFFFF",
    sub: "#F3E8FF",
    profit: "#FFFFFF",
    loss: "#FFE4E6",
    pillBg: "#FFFFFF",
    pillText: "#4C1D95",
    pillBorder: "#FFFFFF",
    divider: "#FFFFFF55",
    shadow: true,
    fallback: ["#7C3AED", "#EC4899"],
    background: undefined,
  },
  grid: {
    label: "Grid",
    text: "#FFFFFF",
    sub: "#7E9CC0",
    profit: "#22D3EE",
    loss: "#F87171",
    pillBg: "#0E2A47",
    pillText: "#22D3EE",
    pillBorder: "#22D3EE",
    divider: "#1E3A5F",
    shadow: false,
    fallback: ["#0F172A", "#0F172A"],
    background: undefined,
  },
  noir: {
    label: "Noir",
    text: "#EDEDED",
    sub: "#8A8A8E",
    profit: "#4ADE80",
    loss: "#F87171",
    pillBg: "#2A2418",
    pillText: "#E8C48A",
    pillBorder: "#5A4A2A",
    divider: "#343436",
    shadow: false,
    fallback: ["#1A1A1B", "#1A1A1B"],
    background: require("../../assets/cards/noir.png"),
  },
  blush: {
    label: "Blush",
    text: "#262222",
    sub: "#6B5C5C",
    profit: "#1F7A3D",
    loss: "#B42318",
    pillBg: "#FAF4F2",
    pillText: "#262222",
    pillBorder: "#2A2626",
    divider: "#2A262633",
    shadow: false,
    fallback: ["#F2C9C8", "#C9A3A3"],
    background: require("../../assets/cards/blush.png"),
  },
  moonlit: {
    label: "Moonlit",
    text: "#FFFFFF",
    sub: "#C9BFF0",
    profit: "#E9DDFF",
    loss: "#FDA4AF",
    pillBg: "#C4B5FD",
    pillText: "#1B0F3D",
    pillBorder: "#C4B5FD",
    divider: "#FFFFFF33",
    shadow: true,
    fallback: ["#0A0618", "#1B0F3D"],
    background: require("../../assets/cards/moonlit.png"),
  },
  gigachad: {
    label: "Gigachad",
    text: "#FFFFFF",
    sub: "#9A9A9A",
    profit: "#FFFFFF",
    loss: "#FF4D4D",
    pillBg: "#FFFFFF",
    pillText: "#000000",
    pillBorder: "#FFFFFF",
    divider: "#FFFFFF33",
    shadow: true,
    fallback: ["#0A0A0A", "#0A0A0A"],
    background: require("../../assets/cards/gigachad.png"),
  },
} as const;

export type CardStyle = keyof typeof CARD_THEMES;

export const CARD_STYLE_LABELS: Record<CardStyle, string> = Object.fromEntries(
  (Object.keys(CARD_THEMES) as CardStyle[]).map((k) => [k, CARD_THEMES[k].label]),
) as Record<CardStyle, string>;
